### ISSUE TITLE
RFC Add feature for user to directly generate benchmark results

### ISSUE THREAD

**Issue by ChuanyuXue** [ChuanyuXue/tsnkit#20]
Currently, users can only call scheduling methods via command line to solve single problem instances. This limits the ability to efficiently compare multiple methods across various scenarios. 

We aim to develop a pipeline for user to call multiple scheduling methods on multiple problem instances and reproduce the table/figures from our paper. 

Example: `python -m tsnkit.benchmark [smt-nw, smt-wa] [1-5, 7-10]`

Related issue: Closed #7 

**TODO:**
- [ ] Define and implement the user API to select which algorithms to use and which data to run.
- [ ] Define and implement the data format to record the algorithm returns (result, runtime, memory usage, ...)
- [ ] Implement the statistic calculation and visualization functions (referring https://github.com/ChuanyuXue/tsnkit/blob/legacy/results.gz)
- [ ] Test and validation
